spring:
  data:
    redis:
      host: 192.168.31.199
      port: 6379
    mongodb:
      uri: mongodb://test:1234@192.168.31.199:27017

  datasource:
    url: jdbc:mysql://192.168.31.199:3306/test?useSSL=false&serverTimezone=UTC
    username: test
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
