spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 219906444543-e1dls6svattsoo5ppraqkdh8uet1j1g9.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code #OAuth? ?? ??? code? ???? ??? ???? ???
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              -

          naver:
            client-name: kakao
            client-id: 334e05fbe76090fa2e3aca4168258577
            client-secret: nrAcaDwEIziQXbzxGsMWfdyonfa0s2XM
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


